# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
